name: Veracode_Go
on:
  workflow_dispatch:

jobs:
  Veracode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Create Vendor Folder
        run: go mod vendor

      - name: Build
        run: go build -v ./...

      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          path: .
      - name: UploadAndScan
        uses: veracode/veracode-uploadandscan-action@master
        env:
          VeracodeID: ${{ secrets.VeracodeID }}
          VeracodeKey: ${{ secrets.VeracodeKey }}
          AppName: ${{ github.repository }}
        with:
          vid: '$VeracodeID'
          vkey: '$VeracodeKey'
          criticality: 'VeryHigh'
          appname: '$AppName'
          createsandbox: true
          filepath: veracode.zip
          deleteIncompleteScan: false
          version: ${{ github.run_id }}