name: Veracode Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  Install-Requeriments:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.0b1-buster
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: install requeriments
      run: |
        python -m pip install --no-cache-dir pip==22.0.4

  Veracode-SCA-Agent-Action:
    runs-on: ubuntu-latest
    needs: [Install-Requeriments]
    container:
      image: python:3.11.0b1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: pip install
        run: |
          python -m pip install --no-cache-dir pip==22.0.4
      
      - name: Listing
        run: |
          ls -lah
      
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: | 
          export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/PyGoat.git"
          export SRCCLR_SCM_REF=${{ github.workflow }}
          export SRCCLR_SCM_REF_TYPE="branch"
          export SRCCLR_SCM_REV=${{ github.run_id }}
        
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS
        
  Veracode-SAST-Policy-Scan:
    runs-on: ubuntu-latest
    needs: [Install-Requeriments, Veracode-SCA-Agent-Action]
    container:
      image: veracode/api-wrapper-java:latest
      options: --user root
    steps:
    - uses: actions/checkout@master

    - name: scan 
      run: |
          zip -r pygoat.zip . -i '*.py' '*.html' '*.js'
          java -jar /opt/veracode/api-wrapper.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" -action UploadAndScan -createprofile false -appname "Pygoat-Showroom" -version "${{ github.run_id }}" -filepath pygoat.zip -scantimeout 20

  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    needs: [Install-Requeriments, Veracode-SCA-Agent-Action]
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: scan 
        run: |
          zip -r -v pygoat.zip . -i '*.py' '*.js' '*.html'  
          java -jar /opt/veracode/pipeline-scan.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" -f pygoat.zip -aid "1242124" -p "PyGoat-Showroom" -pn "Veracode Recommended Medium"
    continue-on-error: true
