name: veracode-scan
on:
  push:
    branches: [feature-1]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: install gems
        run : |
          bundle install --without development test
      
      - name: packaging to veracode scan
        run : |
           bundle update veracode
           veracode prepare -v
      
      - name: rename file packaged
        run : |
            mv tmp/* tmp/veracode-artifact.zip
     
      - name: publishing artifact
        uses: actions/upload-artifact@v2
        with:
          name: veracode-package
          path: tmp/

  veracode-sca:
    name: SCA agent-based
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: sca agent-based scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS

  veracode_static_analysis_sanbox:
    name: SAST Sandbox Scan
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: veracode-package
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'railsgoat-demo'
          createprofile: false
          filepath: 'veracode-artifact.zip'
          vid: '${{ secrets.VID }}'
          vkey: '${{ secrets.VKEY }}'
          createsandbox: 'true'
          sandboxname: 'dev'
          deleteincompletescan: 2

  veracode_static_analysis_policy:
    name: SAST Policy Scan
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: veracode-package
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'railsgoat-demo'
          createprofile: false
          filepath: 'veracode-artifact.zip'
          vid: '${{ secrets.VID }}'
          vkey: '${{ secrets.VKEY }}'
          deleteincompletescan: 2

 