version: 2.1
jobs:
  # Compila o projeto
  build:
    docker:
      - image: cimg/openjdk:8.0.282-node
    working_directory: ~/target
    steps:
      - checkout
      - run:
          name: Run Maven
          command: 'mvn compile package'
      - persist_to_workspace:
          root: ./
          paths:
            - target
            - ./

  veracode_wrapper:
    docker:
      - image: cimg/openjdk:8.0.282-node
    steps:
      - attach_workspace:
          at: ./    
      - run:
          name: "Get the Veracode agent"
          command: |
            wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.2.7.4/vosp-api-wrappers-java-21.2.7.4.jar
      - run:
          name: "Upload to Veracode"
          command: java -jar veracode-wrapper.jar 
              -vid $VeracodeID
              -vkey $VeracodeKey
              -action uploadandscan 
              -appname "Verademo_war_circleci"
              -createprofile true
              -version CircleCI-$CIRCLE_BUILD_NUM 
              -filepath ./target/verademo.war

# Configura o fluxo dos scans
workflows:
  version: 2.1
  build_and_scan:
    jobs:
      - build
      - veracode_wrapper:
          requires:
            - build