pipelines:
  default:
    - step:
        name: Veracode auto-packaging
        image: atlassian/default-image:4
        script:
            - export VERACODE_API_KEY_ID="${VERACODE_ID}"
            - export VERACODE_API_KEY_SECRET="${VERACODE_KEY}"
            - mkdir verascan
            - curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            - ./veracode package --source "${REPO_URL}" --type repo --output verascan --trust
            - ls -l verascan
            - mv verascan/*.zip verascan/upload.zip
        after-script:
          - echo "package for veracode scan ready"
        artifacts:
          - 'verascan/upload.zip'
    - step:
        name: Veracode SCA
        image: node:lts
        script:
          - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor || true
        after-script:
          - echo "Software Composition Analysis done! See the details results in Veracode Platform"
    - step:
        name: Veracode SAST Sandbox Scan
        image: veracode/api-wrapper-java
        script:
          - echo "Veracode SAST Sandbox Scan"
          - java -jar /opt/veracode/api-wrapper.jar
            -action UploadAndScan
            -appname "$BITBUCKET_REPO_SLUG"
            -createprofile true
            -vid "${VERACODE_ID}"
            -vkey "${VERACODE_KEY}"
            -sandboxname "$BITBUCKET_BRANCH"
            -createsandbox true
            -filepath verascan/upload.zip
            -version "Build Number $BITBUCKET_BUILD_NUMBER"
            -deleteincompletescan 2
        after-script:
          - echo "Application artifact sent to Veracode sucessfuly!"          

    - step:
        name: Veracode SAST Policy Scan
        image: veracode/api-wrapper-java
        script:
          - echo "Veracode SAST Policy Scan"
          - ls -l
          - java -jar /opt/veracode/api-wrapper.jar
            -action UploadAndScan
            -appname "$BITBUCKET_REPO_SLUG"
            -createprofile true
            -vid "${VERACODE_ID}"
            -vkey "${VERACODE_KEY}"
            -filepath verascan/upload.zip
            -version "$BITBUCKET_BUILD_NUMBER"
            -deleteincompletescan 2
        after-script:
          - echo "Application artifact sent to Veracode sucessfuly!"
    - step:
        name: Veracode SAST Pipeline Scan
        image: veracode/pipeline-scan
        script:
          - ls -l
          - java -jar /opt/veracode/pipeline-scan.jar --veracode_api_id "${VERACODE_ID}" --veracode_api_key "${VERACODE_KEY}" --file verascan/upload.zip --issue_details true || true