trigger:
- master

pool:
  vmImage: windows-latest

variables:
  veracodeProjectName: AzDevOps.$(Build.DefinitionName)
  caminhoPacote: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  veracodeComponentName: "MicroServico"

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Agent.BuildDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(caminhoPacote)'
    replaceExistingArchive: true
  displayName: 'Criando pacote para analise'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1')) # Faz o download do script
      srcclr scan --update-advisor --allow-dirty # Executa o scan
  displayName: 'Veracode SCA'
  continueOnError: true
  
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '$(VeracodeID)'
    apiKey: '$(VeracodeKey)'
    veracodeAppProfile: '$(veracodeProjectName)'
    version: '$(build.buildNumber)'
    filepath: '$(caminhoPacote)'
    createSandBox: true
    sandboxName: '$(veracodeComponentName)'
    createProfile: true
    failTheBuildIfVeracodeScanDidNotInitiate: false
    scanStatusCheckInterval: '60'
    importResults: false
    failBuildOnPolicyFail: false
  displayName: 'Veracode U&S'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $urlDownload = "https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip"
      $caminhoDownload = "VeracodePipeline.zip" # Define um caminho para o arquivo de download
      Invoke-WebRequest -Uri "$urlDownload" -OutFile "$caminhoDownload" # Faz o download
      Expand-Archive -Path "$caminhoDownload" -DestinationPath "$(Build.ArtifactStagingDirectory)" # Descompacta o ZIP para uma pasta
  displayName: 'Configuracao Pipeline Scan'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'java -jar $(Build.ArtifactStagingDirectory)/pipeline-scan.jar -vid $(VeracodeID) -vkey $(VeracodeKey) -f $(caminhoPacote) --issue_details true'
  displayName: 'Veracode PipelineScan'
