trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  veracodeAppProfile: AzDevOps.$(Build.DefinitionName)
  caminhoPacote: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  timeVeracode: "DEVs"

steps:
- script: |
    curl -o veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/23.4.11.2/vosp-api-wrappers-java-23.4.11.2.jar
  displayName: 'Download Veracode Wrapper'
- script: |
    java -jar veracode-wrapper.jar -vid $(VERACODE_API_KEY_ID) -vkey $(VERACODE_API_KEY_SECRET) -action uploadandscan -appname $(veracodeAppProfile) -createprofile true  -version $(build.buildNumber) -filepath $(caminhoPacote) -teams "$(timeVeracode)" 
  displayName: 'Veracode U&S'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$allApps = java -jar veracode-wrapper.jar -vid $(VERACODE_API_KEY_ID) -vkey $(VERACODE_API_KEY_SECRET) -action GetAppList
      $appList = $allApps.appList.app
      $appID = ($appList | Where-Object { $_.app_name -eq "$(veracodeAppProfile)" }).app_id
      # Faz a modificação de times
      # Valida se existe um App ID
      if ($appID) {
          Write-Host "Add $(veracodeAppProfile) (ID: $appID) in $(timeVeracode)"
          java -jar veracode-wrapper.jar -vid $(VERACODE_API_KEY_ID) -vkey $(VERACODE_API_KEY_SECRET) -action updateapp -appid $appID -teams "$(timeVeracode)"
      } else {
          Write-Host "Não foram encontradas informacoes para o projeto: $(veracodeAppProfile)"
      }
  displayName: 'Define o time na Veracode'