stages:
    - build
    - veracode_sca
    - veracode_iac_scan
    - veracode_sast_sandbox_scan
    - veracode_sast_pipeline_scan
    
build:
    image: node:latest
    stage: build
    only:
        - branches
        - tags
        - merge_requests
    script:
        - npm install
    after_script:
        - ls -l

veracode_sca:
    image: node:latest
    stage: veracode_sca
    script:
         - export EXTRA_ARGS='--update-advisor uri-as-name'
         - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan || true
    dependencies:
      - build

veracode_iac_scan:
    image: node:latest
    stage: veracode_iac_scan
    script:
      -  export VERACODE_API_KEY_ID="${VID}" 
      -  export VERACODE_API_KEY_SECRET="${VKEY}"
      
      -  echo [+] Configuring Veracode IaC Scan
      -  curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      -  ./veracode configure
      
      -  echo [+] Scanning directory
      -  ./veracode scan --source . --type directory --format table
    dependencies:
      - build

veracode_sast_sandbox_scan:
    image: veracode/api-wrapper-java
    stage: veracode_sast_sandbox_scan
    script:
        - zip -r uploadToVeracode.zip . -x "*node_modules" "*.git" -i "*.js"  "*.html"  "*.htm"  "*.ts"  "*.tsx"  "*.json"  "*.css"  "*.jsp"  "*.vue"
        - >
        - java -jar /opt/veracode/api-wrapper.jar
          -action UploadAndScan 
          -appname NodeGoat-Demo
          -createprofile false
          -vid "${VID}"
          -vkey "${VKEY}"
          -sandboxname $CI_COMMIT_REF_NAME 
          -createsandbox true
          -filepath uploadToVeracode.zip
          -version "job ${CI_JOB_ID}"
          -deleteincompletescan 2
    dependencies:
        - build
        - veracode_sca
        - veracode_iac_scan

veracode_sast_policy_scan:
    image: veracode/api-wrapper-java
    stage: veracode_sast_sandbox_scan
    script:
        - zip -r uploadToVeracode.zip . -x "*node_modules" "*.git" -i "*.js"  "*.html"  "*.htm"  "*.ts"  "*.tsx"  "*.json"  "*.css"  "*.jsp"  "*.vue"
        - >
        - java -jar /opt/veracode/api-wrapper.jar
          -action UploadAndScan 
          -appname NodeGoat-Demo
          -createprofile false
          -vid "${VID}"
          -vkey "${VKEY}"
          -filepath uploadToVeracode.zip
          -version "job ${CI_JOB_ID}"
          -deleteincompletescan 2
    dependencies:
        - build
        - veracode_sast_sandbox_scan

veracode_sast_pipeline_scan:
  image: veracode/pipeline-scan:latest
  stage: veracode_sast_pipeline_scan
  script:
    - zip -r uploadToVeracode.zip . -x "*node_modules" "*.git" -i "*.js"  "*.html"  "*.htm"  "*.ts"  "*.tsx"  "*.json"  "*.css"  "*.jsp"  "*.vue"
    - >
    - java -jar /opt/veracode/pipeline-scan.jar 
        -vid "${VID}" 
        -vkey "${VKEY}"
        --file uploadToVeracode.zip
        --policy_name "Veracode Recommended Medium"
  dependencies:
      - build
      - veracode_sast_policy_scan
