stages:
    - build
    - veracode_sca
    - veracode_iac_scan
    - veracode_sast_sandbox_scan
    - veracode_sast_policy_scan
    - veracode_sast_pipeline_scan
    
build:
    image: maven:3.8.1-jdk-11
    stage: build
    only:
        - branches
        - tags
        - merge_requests
    script:
        - mvn clean package
    after_script:
        - ls -l ./target
    artifacts:
        paths:
            - /builds/lucas.ferreira4/Verademo_Java/target/verademo.war


#sca_security_scanning:
#    image: maven:3.8.1-jdk-11
#    stage: sca_security_scanning
#    script:
#         - export SRCCLR_DEPENDENCY_TREE_FILE=tree.txt
#         - mvn dependency:tree > tree.txt
#         - cat tree.txt
#         - curl -sSL https://download.sourceclear.com/ci.sh | bash -s test --maven
#         - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor --stdin=maven
#    dependencies:
#      - build

veracode_iac_scan:
    image: maven:3.8.1-jdk-11
    stage: veracode_iac_scan
    script:
      -  export VERACODE_API_KEY_ID="${VID}" 
      -  export VERACODE_API_KEY_SECRET="${VKEY}"
      
      -  echo [+] Configuring Veracode IaC Scan
      -  curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      -  ./veracode configure
      
      -  echo [+] Scanning directory
      -  ./veracode scan --source . --type directory --format table
    dependencies:
      - build

veracode_sca:
    image: maven:3.8.1-jdk-11
    stage: veracode_sca
    script:
         - export EXTRA_ARGS='--update-advisor uri-as-name'
         - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan || true
    dependencies:
      - build

veracode_sast_sandbox_scan:
    image: veracode/api-wrapper-java
    stage: veracode_sast_sandbox_scan
    script:
        - >
        - java -jar /opt/veracode/api-wrapper.jar
          -action UploadAndScan 
          -appname Java-VeraDemo
          -createprofile false
          -vid "${VID}"
          -vkey "${VKEY}"
          -sandboxname $CI_COMMIT_REF_NAME 
          -createsandbox true
          -filepath target/verademo.war
          -version "job ${CI_JOB_ID}"
          -deleteincompletescan 2
    dependencies:
        - build

veracode_sast_policy_scan:
    image: veracode/api-wrapper-java
    stage: veracode_sast_policy_scan
    script:
        - >
        - java -jar /opt/veracode/api-wrapper.jar
          -action UploadAndScan
          -vid "${VID}"
          -vkey "${VKEY}"
          -appname Java-VeraDemo
          -createprofile false
          -autoscan true
          -filepath target/verademo.war
          -version "job ${CI_JOB_ID}"
          -deleteincompletescan 2
    dependencies:
        - build
        - veracode_sast_sandbox_scan

veracode_sast_pipeline_scan:
  image: veracode/pipeline-scan:latest
  stage: veracode_sast_pipeline_scan
  script:
    - >
    - java -jar /opt/veracode/pipeline-scan.jar 
        -vid "${VID}" 
        -vkey "${VKEY}"
        --file target/verademo.war
        --policy_name "Veracode Recommended High"
  dependencies:
      - build
      - veracode_sast_sandbox_scan
