stages:
    - build
    - veracode_sca
    - veracode_sast_sandbox_scan
    - veracode_sast_policy_scan
    - veracode_sast_pipeline_scan

variables:
    Caminho_dlls: "/builds/lucas.ferreira4/WebGoat-Net/WebGoat/bin/"

build:
    image: mono:latest
    stage: build
    only:
        - branches
        - tags
        - merge_requests
    script:
        - xbuild
    after_script:
        - ls -l /builds/lucas.ferreira4/WebGoat-Net/WebGoat/
        - ls -l /builds/lucas.ferreira4/WebGoat-Net/WebGoat/bin
    artifacts:
        paths:
            - $Caminho_dlls

veracode_sca:
    image: maven:3.8.1-jdk-11
    stage: veracode_sca
    script:
         - export EXTRA_ARGS='--update-advisor uri-as-name'
         - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS || true
    dependencies:
      - build

veracode_sast_sandbox_scan:
    image: veracode/api-wrapper-java
    stage: veracode_sast_sandbox_scan
    script:
        - zip -r uploadToVeracode.zip $Caminho_dlls
        - >
        - java -jar /opt/veracode/api-wrapper.jar
          -action UploadAndScan 
          -appname WebGoat-dotNET
          -createprofile false
          -vid "${VID}"
          -vkey "${VKEY}"
          -sandboxname $CI_COMMIT_REF_NAME 
          -createsandbox true
          -filepath uploadToVeracode.zip
          -version "job ${CI_JOB_ID}"
          -deleteincompletescan 2
    dependencies:
        - build
        - veracode_sca

veracode_sast_policy_scan:
    image: veracode/api-wrapper-java
    stage: veracode_sast_policy_scan
    script:
        - zip -r uploadToVeracode.zip $Caminho_dlls
        - >
        - java -jar /opt/veracode/api-wrapper.jar
          -action UploadAndScan
          -vid "${VID}"
          -vkey "${VKEY}"
          -appname WebGoat-dotNET
          -createprofile false
          -autoscan true
          -filepath uploadToVeracode.zip
          -version "job ${CI_JOB_ID}"
          -deleteincompletescan 2
    dependencies:
        - build
        - veracode_sast_sandbox_scan

veracode_sast_pipeline_scan:
  image: veracode/pipeline-scan:latest
  stage: veracode_sast_pipeline_scan
  script:
    - zip -r uploadToVeracode.zip $Caminho_dlls
    - >
    - java -jar /opt/veracode/pipeline-scan.jar --include DotNetGoat*
        -vid "${VID}" 
        -vkey "${VKEY}"
        --file uploadToVeracode.zip
        --policy_name "Veracode Recommended High"
  dependencies:
      - build
      - veracode_sast_policy_scan
